### ISSUE TITLE
Unable to find RC.exe

### ISSUE THREAD

**Issue by David-OConnor** [nabijaczleweli/rust-embed-resource#10]
This is a cross-post from [this](https://github.com/thecoshman/http/issues/68) https crate issue.

This crate seems sensitive to C-compiler setup; failing on Windows 10 when running `cargo install https`. I think it's trying to find a Visual Studio compiler that is not normally in the system path.
```
error: failed to run custom build command for `https v1.3.2`
process didn't exit successfully: `C:\Users\david\AppData\Local\Temp\cargo-install9Sgt9O\release\build\https-b1afe7e63ae
4afd0\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Are you sure you have RC.EXE in your $PATH?: Os { code: 2, kind: NotFound, message: "The syst
em cannot find the file specified." }', libcore\result.rs:945:5
```

**Comment by nabijaczleweli** [comment]
What do you get if you set `RUST_BACKTRACE=full`?

**Comment by David-OConnor** [comment]
Not sure how to get that command to work, but here's the rest:


`stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:350
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:328
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed
  10: embed_resource::windows_msvc::compile_resource
  11: embed_resource::compile
  12: main
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  18: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  22: BaseThreadInitThunk
  23: RtlUserThreadStart`

**Comment by nabijaczleweli** [comment]
I'm guessing you're using the MSVC stack, then?

**Comment by David-OConnor** [comment]
No; just Cargo.

**Comment by nabijaczleweli** [comment]
Okay then, where do you have `rc.exe` on your computer (and does it work if you run the `vcvars.bat` thingy)?

**Comment by nabijaczleweli** [comment]
Turns out Jon Blow has [a copy-pastable "library"](https://pastebin.com/3YvWQa5c) that's a much more generic version of our VS acquisition code, but oh boy am I not looking forward to porting it.

**Comment by thecoshman** [comment]
Is there an ETA for this :)

**Comment by nabijaczleweli** [comment]
Funny you should ask, I just earlier today opened the aforelinked pastebin! Maybe I'll just link to it, which means I don't have to rewrite it :v

**Comment by thecoshman** [comment]
I just read the opening 'easy' on how as bad as that code is, it's actually really good despite all the pressure on it to be worse... 😢 

Good luck with it! 👍

**Comment by nabijaczleweli** [comment]
@David-OConnor What do you get when you run the `detect` example from https://github.com/nabijaczleweli/vswhom.rs? What is the path to `rc.exe` on your system>

**Comment by nabijaczleweli** [comment]
Okay, then, what output do you get from running `cargo run --example detect` in that folder?

**Comment by David-OConnor** [comment]
```
Some(
    VsFindResult {
        windows_sdk_version: 10,
        windows_sdk_root: Some(
            "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.17134.0"
        ),
        windows_sdk_um_library_path: Some(
            "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.17134.0\\um\\x64"
        ),
        windows_sdk_ucrt_library_path: Some(
            "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.17134.0\\ucrt\\x64"
        ),
        vs_exe_path: Some(
            "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\
\bin\\Hostx64\\x64"
        ),
        vs_library_path: Some(
            "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\
\lib\\x64"
        )
    }
)
```

**Comment by nabijaczleweli** [comment]
Okay, @David-OConnor, can you clone this repository and execute `cargo run -- empty-resource.rc` in it?

**Comment by nabijaczleweli** [comment]
Released in [`v1.2.0`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.2.0) (doesn't mean I'm still not waiting on the tests).

**Comment by David-OConnor** [comment]
Appears to be fixed

**Comment by nabijaczleweli** [comment]
Damn, I'm old.
