### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by crlf0710** [nabijaczleweli/rust-embed-resource#12]
Maybe release a new version so i can finally get rid of the winapi 0.2 dependencies from tree?

**Comment by nabijaczleweli** [comment]
Ah yeah, must've either forgotten or was waiting on some tests. Out in a jiffy!

**Comment by nabijaczleweli** [comment]
Ah, yes, I was waiting on #10.

**Comment by nabijaczleweli** [comment]
Released in [`v1.2.0`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.2.0).
