### ISSUE TITLE
Better documentation for getting started w/ manifests

### ISSUE THREAD

**Issue by jpoles1** [nabijaczleweli/rust-embed-resource#15]
Per the discussion on this [issue](https://github.com/rust-lang/rust/issues/11207) on the Rust lang repo, I think that this repo is posed to serve as a great way to embed windows manifests into Rust executables.

I wrote up some [quick instructions](https://github.com/rust-lang/rust/issues/11207#issuecomment-573924896) for how to include a basic manifest, as I had a bit of trouble doing so with the information available in this repo. Wondering if the maintainers (@nabijaczleweli) would like something similar to be included in the readme or elsewhere in the docs! Would be happy to submit a PR if so.

**Comment by nabijaczleweli** [comment]
Apologies for the delay, but, sure, expanding the Quickstart sexion of the README would be lovely!

**Comment by nabijaczleweli** [comment]
Implemented in #16

**Comment by nabijaczleweli** [comment]
Released in [`v1.3.2`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.3.2).
