### ISSUE TITLE
Clarify naming and pathing rules

### ISSUE THREAD

**Issue by passcod** [nabijaczleweli/rust-embed-resource#21]
The documentation is pretty laconic so I did as it said but are there any hard rules on how the files must be named and where they have to be located? E.g. if I wanted to have the manifest under src/ would that break the build?

**Comment by nabijaczleweli** [comment]
The documentation was laconic because there's nothing to document, really, it just needs to be reachable and relative to the crate root, so, yes, `src/whomever.rc` should also work. I've updated the documentation with this (69b1914a4c1fb66af2109bd5ba3fe73b6bddab9c).

**Comment by nabijaczleweli** [comment]
Released in [`v1.3.4`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.3.4)
