### ISSUE TITLE
Support using llvm-rc to compile RC files

### ISSUE THREAD

**Issue by roblabla** [nabijaczleweli/rust-embed-resource#29]
LLVM has its own RC file compiler called llvm-rc. It's available on Ubuntu 20.04, simply `apt install llvm`. This could be used instead of windres if it is found.

**Comment by nabijaczleweli** [comment]
Released in [`v1.5.0`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v1.5.0).
