### ISSUE TITLE
rust-embed-resource does nothing when crosscompilation for Windows is used on the Linux platform

### ISSUE THREAD

**Issue by application-developer-DA** [nabijaczleweli/rust-embed-resource#3]
My build script is running on a Linux machine and it basically builds executables for Windows (using crosscompilation, i.e. the target is specified explicitly), in such cases `ember-resource` does nothing and does not try to use `windres` from `MinGW` toolkit.

**Comment by nabijaczleweli** [comment]
Normally I'd've used `target_os="windows"` but I used `windows` as condition instead for some reason.

**Comment by application-developer-DA** [comment]
I've just fixed it and sent a pull request.

**Comment by nabijaczleweli** [comment]
A little fast on the trigger there, cowboy. Try again, but on the correct `master` this time.

**Comment by application-developer-DA** [comment]
> Try the PR again, but on the correct master this time.

Actually I did use the **correct** `master` even the first time. You've added a new commit several minutes after the pull requset had been already sent.

**Comment by nabijaczleweli** [comment]
Even if, that PR is garbage in that it asserts *every non-Windows user is crossing for Windows*. There's one roughly okay thing about it, I'll give you that, and it's movable to the correct file, but in its current form? nah

**Comment by application-developer-DA** [comment]
> Even if, that PR is garbage

The pull requests provides a fix for the issue and the changes are written in a way it was possible to write them according to the current source code in your repository. You called it "garbage" while closing the issue with a commit which does **literally nothing** to fix this issue.

> it asserts every non-Windows user is crossing for Windows.

It does not assert anything like that. Your crate in any case works for Windows only, it does compile for other platforms (without even a warning if the platform is not supported), the only thing I changed -- I added the possibility for every user who uses non-windows platform to be able to compile for Windows using crosscompilation (which would also embed the resource file).

**Comment by nabijaczleweli** [comment]
> provides a fix 

In the same fashion that murdering all communists is a fix for communism.

> does literally nothing to fix 

Well it uses `windres` when cross-compiling to Windows, so... Yes it does?

> does not assert 

```rust
pub static SUPPORTED: bool = true;
```

Oh wait, it does. And it also prints a terribly worded warning in the Very General case.

> works for Windows 

No, it works on *all platforms* and does the *only reasonable thing* on ones where resource embedding doesn't exist as a concept.

> added the possibility 

> able to compile for Windows 

Nononono, you *asserted* that every single on-Linux compilation is a cross for Windows and threw a badly worded error otherwise.

**Comment by application-developer-DA** [comment]
> pub static SUPPORTED: bool = true;
> Oh wait, it does.

I'm not the one to blame for the library "architecture" and the way you decided to separate the modules. My change was just a sensible and quick way to make it work properly for crosscompilation. You have not suggested anything better so far.

> No, it works on all platforms and does the only reasonable thing on ones where resource embedding doesn't exist as a concept.

How did it behave before my pull request? - It behaved the same way, except that it did not give you any warning in case if you use the platform which does not support the resource embedding **and** it did nothing if the user tries to crosscompile for Windows from the Linux, Mac machine.

> And it also prints a terribly worded warning in the Very General case.

If you did not like the text for the warning, you could have written what would you like to see changed instead of blowing up this discussion.

>> does literally nothing to fix

> Well it uses windres when cross-compiling to Windows, so... Yes it does?

No it does not. Why do you think that `windres` will be called? You'd better check how your crate and the build dependencies work together before calling the work of other people as garbage.
