### ISSUE TITLE
question: Editing existing .exe?

### ISSUE THREAD

**Issue by zkat** [nabijaczleweli/rust-embed-resource#36]
Is it possible to use this, or one of its related tools, to edit an existing .exe's resource data?

**Comment by nabijaczleweli** [comment]
This is a wrapper around windres and ld arguments, so no; you probably want something like [Resource Hacker](http://www.angusj.com/resourcehacker/), I haven't had problems with it.

**Comment by zkat** [comment]
Thanks!
