### ISSUE TITLE
Feature request: preprocessor defines

### ISSUE THREAD

**Issue by kb-1000** [nabijaczleweli/rust-embed-resource#52]
If I have multiple binaries in one project and want to share the rc files between them, I would end up with the same file description (just like in a java distribution). Using the preprocessor, I could tell it which binary it is and have a `#if` in the rc file.
windres appears to be using --define for this, while rc uses /D.

**Comment by nabijaczleweli** [comment]
Can you try the new `master` branch (at least a05887139bf195308d219352933863436e6ef4e8)? Just adding your list of macros to the end of the `compile[_for]()` call should work.

**Comment by kb-1000** [comment]
Haven't been able to test this yet, but it's worth noting this would be a breaking change, and adding more parameters this way (like... include directories) would require further breaking changes in the future. What would you think about doing it more builder style like the cc crate?

**Comment by nabijaczleweli** [comment]
Yes, I have v2.0.0 tagged locally pending reporter confirmation. The last major bump (0.1.1 -> 1.1.0; 1.0.1 and 1.0.0 didn't happen (defined as being massive fuckups, IIRC)) was in January 2017; I think I can deal with one major bump every six years.

**Comment by nabijaczleweli** [comment]
Works for me; released despite reporter silence in [`v2.0.0`](https://github.com/nabijaczleweli/rust-embed-resource/releases/tag/v2.0.0).
