### ISSUE TITLE
Command prompt icon low resolution

### ISSUE THREAD

**Issue by lesleyrs** [nabijaczleweli/rust-embed-resource#56]
Hi I used this crate to add a file icon to an executable like this https://bevy-cheatbook.github.io/platforms/windows.html?highlight=ico#setting-the-exe-icon

But I noticed that besides the file, you also get a task bar icon in release builds and in command prompt title bar.

I don't mind that but it seems that I can't get the command prompt icon high resolution even if I increase the .ico base resolution, refresh screen, restart pc to clear cache etc. It stays low resolution, any idea?

![image](https://user-images.githubusercontent.com/19632758/233697286-8167318f-9804-4e5d-b9ac-ce726f376a78.png)

**Comment by nabijaczleweli** [comment]
idk who wrote that, you don't need the if; the ico looks like it has all mipmaps up to 256x; this looks like r-e-r works fine, and anything more is squarely in the "make the manifest different" domain, which I can't help you with

(that said, I'd try removing all mipmap except the 256x one to see if it helps. or spec `#![windows_subsystem = "windows"]` to kill the cmd.exe window altogether)

https://github.com/nabijaczleweli/poke-a-mango/blob/master/build.rs
https://github.com/nabijaczleweli/poke-a-mango/blob/master/poke-a-mango-manifest.rc
https://github.com/nabijaczleweli/poke-a-mango/blob/master/assets/poke-a-mango.ico

**Comment by lesleyrs** [comment]
What's r-e-r? Removing all but 256 seems to have worked though thanks!

Kind of strange that the similar sized icon in file explorer looks sharp when the cmd one didn't though.

I do disable the console in release builds so it's not a big deal, but I keep it for debug.

**Comment by nabijaczleweli** [comment]
r-e-r as in rust-embed-resource
