### ISSUE TITLE
It is recommended to support .mc (mc.exe) files.

### ISSUE THREAD

**Issue by kouzhudong** [nabijaczleweli/rust-embed-resource#59]
https://learn.microsoft.com/en-us/windows/win32/eventlog/message-files
https://learn.microsoft.com/en-us/windows/win32/eventlog/message-text-files
https://learn.microsoft.com/en-us/windows/win32/eventlog/sample-message-text-file

**Comment by nabijaczleweli** [comment]
Closing as "no clue what this is".
