### ISSUE TITLE
How to include windows.h in resource.rc file?

### ISSUE THREAD

**Issue by chrde** [nabijaczleweli/rust-embed-resource#8]
I am trying to define a simple dialog in a resource.rc, and certain variables, e.g: `DS_SETFONT` are defined in  windows.h
```
#include <windows.h>
IDD_ABOUTBOX DIALOGEX 0, 0, 170, 62
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION "About demoResources"
FONT 8, "MS Shell Dlg", 0, 0, 0x1
BEGIN
    ICON            IDR_MAINFRAME,IDC_STATIC,14,14,21,20
    LTEXT           "demoResources, Version 1.0",IDC_STATIC,42,14,114,8,SS_NOPREFIX
    LTEXT           "Copyright (C) 2018",IDC_STATIC,42,26,114,8
    DEFPUSHBUTTON   "OK",IDOK,113,41,50,14,WS_GROUP
END
```
I tried to add the env variable
`cargo:include=C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um)`
but it still fails with
`fatal error RC1015: cannot open include file 'windows.h'.`

**Comment by chrde** [comment]
As a workaround (or solution? ), running the appropriate `vcvars*.bat` in the terminal works just fine.

**Comment by nabijaczleweli** [comment]
The only error I'm getting is `windres: resource.rc:7: syntax error`, so 🤔. What does your `windres` say?

**Comment by chrde** [comment]
`windres` is only for the mingw toolchain, isn't it? I use msvc instead

**Comment by nabijaczleweli** [comment]
Ah, right. So, anyway, what were you trying to accomplish with `cargo:include=non-path` (or, well, `cargo:include` en general)?

**Comment by chrde** [comment]
I don't know how `rc.exe` picks up these headers (e.g: `windows.h` ) since in VS you just include the SDK folders in the project, so using cargo:include was my attempt of doing the same.
Any way, running `vcvars64.bat` in the terminal does the trick, so we can mark this as closed :smile:

**Comment by nabijaczleweli** [comment]
As you wish!
